name: tests
on: [push, pull_request]

jobs:
  tests:
    strategy:
      matrix:
        go-version:
          - "1.18"
          - "oldstable"
          - "stable"

    name: "tests (Go: ${{ matrix.go-version }})"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - run: go test -v ./...
